---
oval_user: "oval" 
oval_uid: "1000" 
oval_group: "oval"
oval_gid: "1000" 
uwsgi_port: 30000
app_dir: "/home/{{oval_user}}/oval"
venv_dir: "{{app_dir}}/venv"
oval_vars: "/home/{{oval_user}}/.oval_vars"
git_repo: "https://github.com/jyundt/oval.git"
