"""Add strava_id to Racer

Revision ID: 0e0c69ae4a91
Revises: d6015ee1d632
Create Date: 2016-04-29 14:37:04.162908

"""

# revision identifiers, used by Alembic.
revision = '0e0c69ae4a91'
down_revision = 'd6015ee1d632'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racer', sa.Column('strava_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'racer', ['strava_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'racer', type_='unique')
    op.drop_column('racer', 'strava_id')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    )
    ### end Alembic commands ###
