"""initial migration

Revision ID: 342963b817d6
Revises: None
Create Date: 2016-04-15 14:58:46.729077

"""

# revision identifiers, used by Alembic.
revision = '342963b817d6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('starters', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'starters')
    ### end Alembic commands ###
