"""initial migration

Revision ID: 342963b817d6
Revises: None
Create Date: 2016-04-15 14:58:46.729077

"""

# revision identifiers, used by Alembic.
revision = '342963b817d6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('marshal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('official',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('race_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('racer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('usac_license', sa.Integer(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usac_license')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('slow_lap', sa.Interval(), nullable=True),
    sa.Column('fast_lap', sa.Interval(), nullable=True),
    sa.Column('average_lap', sa.Interval(), nullable=True),
    sa.Column('weather', sa.String(length=200), nullable=True),
    sa.Column('usac_permit', sa.String(length=200), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('starters', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['race_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('racer_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('team_points', sa.Integer(), nullable=True),
    sa.Column('mar_points', sa.Integer(), nullable=True),
    sa.Column('mar_place', sa.Integer(), nullable=True),
    sa.Column('point_prime', sa.Boolean(), nullable=True),
    sa.Column('dnf', sa.Boolean(), nullable=True),
    sa.Column('dns', sa.Boolean(), nullable=True),
    sa.Column('relegated', sa.Boolean(), nullable=True),
    sa.Column('disqualified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['racer_id'], ['racer.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_marshal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marshal_id', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marshal_id'], ['marshal.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_official',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['official_id'], ['official.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prime')
    op.drop_table('race_official')
    op.drop_table('race_marshal')
    op.drop_table('participant')
    op.drop_table('race')
    op.drop_table('team')
    op.drop_table('racer')
    op.drop_table('race_class')
    op.drop_table('official')
    op.drop_table('marshal')
    op.drop_table('admin')
    ### end Alembic commands ###
