"""Add default attribute to Course

Revision ID: 3abfb50ea134
Revises: a1c445cca793
Create Date: 2016-09-10 16:33:40.634668

"""

# revision identifiers, used by Alembic.
revision = '3abfb50ea134'
down_revision = 'a1c445cca793'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('is_default', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'is_default')
    ### end Alembic commands ###
