"""Remove season pass class -- boolean only

Revision ID: 456cc02b1824
Revises: a5b02b61db39
Create Date: 2017-04-12 08:16:41.227748

"""

# revision identifiers, used by Alembic.
revision = '456cc02b1824'
down_revision = 'a5b02b61db39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'aca_membership_season_pass_fkey', 'aca_membership', type_='foreignkey')
    op.alter_column('aca_membership', 'season_pass',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               postgresql_using='''season_pass is not null''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aca_membership', 'season_pass', nullable=True)
    op.alter_column('aca_membership', 'season_pass',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               postgresql_using='''null''')
    op.create_foreign_key(u'aca_membership_season_pass_fkey', 'aca_membership', 'race_class', ['season_pass'], ['id'])
    # ### end Alembic commands ###
