"""Rename AdminRoles to AdminRole and fix backref.

Revision ID: 561431f51d19
Revises: 9bf3d217470a
Create Date: 2016-04-19 09:21:08.726307

"""

# revision identifiers, used by Alembic.
revision = '561431f51d19'
down_revision = '9bf3d217470a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admin_roles')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], [u'admin.id'], name=u'admin_roles_admin_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], [u'role.id'], name=u'admin_roles_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'admin_roles_pkey')
    )
    op.drop_table('admin_role')
    ### end Alembic commands ###
