"""Add Winning Time to Race model.

Revision ID: 5794d34e6b61
Revises: 2a9524c8b700
Create Date: 2016-05-24 07:02:04.062103

"""

# revision identifiers, used by Alembic.
revision = '5794d34e6b61'
down_revision = '2a9524c8b700'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('winning_time', sa.Interval(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'winning_time')
    ### end Alembic commands ###
