"""Add points_dropped column

Revision ID: 5c36a72506a6
Revises: 47f8e5a2a153
Create Date: 2018-08-25 08:55:16.744942

"""

# revision identifiers, used by Alembic.
revision = '5c36a72506a6'
down_revision = '47f8e5a2a153'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('points_dropped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'points_dropped')
    # ### end Alembic commands ###
