"""Rename current_team to current_team_id

Revision ID: 628b5fe65b72
Revises: a14e1ddd71e2
Create Date: 2016-04-21 11:06:27.786845

"""

# revision identifiers, used by Alembic.
revision = '628b5fe65b72'
down_revision = 'a14e1ddd71e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racer', sa.Column('current_team_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'racer_current_team_fkey', 'racer', type_='foreignkey')
    op.create_foreign_key(None, 'racer', 'team', ['current_team_id'], ['id'])
    op.drop_column('racer', 'current_team')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racer', sa.Column('current_team', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'racer', type_='foreignkey')
    op.create_foreign_key(u'racer_current_team_fkey', 'racer', 'team', ['current_team'], ['id'])
    op.drop_column('racer', 'current_team_id')
    ### end Alembic commands ###
