"""empty message

Revision ID: a1c445cca793
Revises: d7241b15a34d
Create Date: 2016-09-03 08:54:28.221701

"""

# revision identifiers, used by Alembic.
revision = 'a1c445cca793'
down_revision = 'd7241b15a34d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('length_miles', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'length_miles')
    ### end Alembic commands ###
