"""ACA membership table (membership by year and season passes)

Revision ID: a5b02b61db39
Revises: 3abfb50ea134
Create Date: 2017-03-07 21:28:55.237254

"""

# revision identifiers, used by Alembic.
revision = 'a5b02b61db39'
down_revision = '3abfb50ea134'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aca_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('racer_id', sa.Integer(), nullable=True),
    sa.Column('season_pass', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['racer_id'], ['racer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_pass'], ['race_class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('racer_id', 'year', name='uniq_member_year')
    )
    op.drop_column(u'racer', 'aca_member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'racer', sa.Column('aca_member', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('aca_membership')
    # ### end Alembic commands ###
