"""Re-readding the delete constraint in Admin Role.

Revision ID: c52b17f09a01
Revises: f2fdab5c2ad0
Create Date: 2016-04-19 14:11:15.009793

"""

# revision identifiers, used by Alembic.
revision = 'c52b17f09a01'
down_revision = 'f2fdab5c2ad0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'admin_role_role_id_fkey', 'admin_role', type_='foreignkey')
    op.drop_constraint(u'admin_role_admin_id_fkey', 'admin_role', type_='foreignkey')
    op.create_foreign_key(None, 'admin_role', 'admin', ['admin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'admin_role', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_role', type_='foreignkey')
    op.drop_constraint(None, 'admin_role', type_='foreignkey')
    op.create_foreign_key(u'admin_role_admin_id_fkey', 'admin_role', 'admin', ['admin_id'], ['id'])
    op.create_foreign_key(u'admin_role_role_id_fkey', 'admin_role', 'role', ['role_id'], ['id'])
    ### end Alembic commands ###
