"""Update Racer model for Strava integration.

Revision ID: d7241b15a34d
Revises: e8ae58376633
Create Date: 2016-08-17 15:12:57.125419

"""

# revision identifiers, used by Alembic.
revision = 'd7241b15a34d'
down_revision = 'e8ae58376633'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racer', sa.Column('strava_access_token', sa.String(length=40), nullable=True))
    op.add_column('racer', sa.Column('strava_email', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'racer', ['strava_access_token'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'racer', type_='unique')
    op.drop_column('racer', 'strava_email')
    op.drop_column('racer', 'strava_access_token')
    ### end Alembic commands ###
