"""Add course type to database schema.

Revision ID: e316df277b2f
Revises: dc435d7f9239
Create Date: 2016-05-04 13:33:11.670160

"""

# revision identifiers, used by Alembic.
revision = 'e316df277b2f'
down_revision = 'dc435d7f9239'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_column(u'admin', 'name')
    op.add_column(u'race', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'race', 'course', ['course_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'race', type_='foreignkey')
    op.drop_column(u'race', 'course_id')
    op.add_column(u'admin', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_table('course')
    ### end Alembic commands ###
