---
- name: Restart uWSGI
  service: name=uwsgi state=restarted

- name: Upgrade DB schema
  shell: "source /home/{{oval_user}}/.bashrc ; . {{venv_dir}}/bin/activate &&  {{app_dir}}/manage.py db upgrade"
  args:
    chdir: "{{app_dir}}"
  become: true
  become_user: "{{oval_user}}"
