- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: target hostname or IP
    private: no
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: hostlist

- name: deploy
  hosts: hostlist
  remote_user: root
  roles:
    - role: base
      firewall_exceptions:
        - "http"
        - "https"
    - role: db
    - role: app
      db_host: "127.0.0.1"
    - role: web
      app_server: "127.0.0.1"
